---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relay.secureai.dev
  resources:
  - agentpolicies
  - toolpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - relay.secureai.dev
  resources:
  - agentsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relay.secureai.dev
  resources:
  - agentsessions/finalizers
  verbs:
  - update
- apiGroups:
  - relay.secureai.dev
  resources:
  - agentsessions/status
  verbs:
  - get
  - patch
  - update
