apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-controller-manager
  namespace: relay-system
  labels:
    app.kubernetes.io/name: relay
    app.kubernetes.io/component: controller-manager
