//go:build !ignore_autogenerated

/*
Copyright 2026 The Relay Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicy) DeepCopyInto(out *AgentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicy.
func (in *AgentPolicy) DeepCopy() *AgentPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyList) DeepCopyInto(out *AgentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyList.
func (in *AgentPolicyList) DeepCopy() *AgentPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicySpec) DeepCopyInto(out *AgentPolicySpec) {
	*out = *in
	in.PolicyRules.DeepCopyInto(&out.PolicyRules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicySpec.
func (in *AgentPolicySpec) DeepCopy() *AgentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyStatus) DeepCopyInto(out *AgentPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyStatus.
func (in *AgentPolicyStatus) DeepCopy() *AgentPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSession) DeepCopyInto(out *AgentSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSession.
func (in *AgentSession) DeepCopy() *AgentSession {
	if in == nil {
		return nil
	}
	out := new(AgentSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionList) DeepCopyInto(out *AgentSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionList.
func (in *AgentSessionList) DeepCopy() *AgentSessionList {
	if in == nil {
		return nil
	}
	out := new(AgentSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionSpec) DeepCopyInto(out *AgentSessionSpec) {
	*out = *in
	in.Task.DeepCopyInto(&out.Task)
	in.Model.DeepCopyInto(&out.Model)
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.PolicyRefs != nil {
		in, out := &in.PolicyRefs, &out.PolicyRefs
		*out = make([]PolicyRef, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeProfileRef != nil {
		in, out := &in.RuntimeProfileRef, &out.RuntimeProfileRef
		*out = new(RuntimeProfileRef)
		**out = **in
	}
	in.Policy.DeepCopyInto(&out.Policy)
	out.Workspace = in.Workspace
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionSpec.
func (in *AgentSessionSpec) DeepCopy() *AgentSessionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionStatus) DeepCopyInto(out *AgentSessionStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchedPolicies != nil {
		in, out := &in.MatchedPolicies, &out.MatchedPolicies
		*out = make([]MatchedPolicyRef, len(*in))
		copy(*out, *in)
	}
	if in.EffectivePolicy != nil {
		in, out := &in.EffectivePolicy, &out.EffectivePolicy
		*out = new(EffectivePolicyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyDecisions != nil {
		in, out := &in.PolicyDecisions, &out.PolicyDecisions
		*out = make([]PolicyDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchedRuntimeProfile != nil {
		in, out := &in.MatchedRuntimeProfile, &out.MatchedRuntimeProfile
		*out = new(MatchedRuntimeProfileRef)
		**out = **in
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(SessionResult)
		**out = **in
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(SessionUsage)
		**out = **in
	}
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]PolicyViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]ArtifactRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionStatus.
func (in *AgentSessionStatus) DeepCopy() *AgentSessionStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactRef) DeepCopyInto(out *ArtifactRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactRef.
func (in *ArtifactRef) DeepCopy() *ArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivePolicyStatus) DeepCopyInto(out *EffectivePolicyStatus) {
	*out = *in
	in.PolicyRules.DeepCopyInto(&out.PolicyRules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivePolicyStatus.
func (in *EffectivePolicyStatus) DeepCopy() *EffectivePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EffectivePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlinePolicySpec) DeepCopyInto(out *InlinePolicySpec) {
	*out = *in
	in.PolicyRules.DeepCopyInto(&out.PolicyRules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlinePolicySpec.
func (in *InlinePolicySpec) DeepCopy() *InlinePolicySpec {
	if in == nil {
		return nil
	}
	out := new(InlinePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedPolicyRef) DeepCopyInto(out *MatchedPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedPolicyRef.
func (in *MatchedPolicyRef) DeepCopy() *MatchedPolicyRef {
	if in == nil {
		return nil
	}
	out := new(MatchedPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedRuntimeProfileRef) DeepCopyInto(out *MatchedRuntimeProfileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedRuntimeProfileRef.
func (in *MatchedRuntimeProfileRef) DeepCopy() *MatchedRuntimeProfileRef {
	if in == nil {
		return nil
	}
	out := new(MatchedRuntimeProfileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(string)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputSpec) DeepCopyInto(out *OutputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputSpec.
func (in *OutputSpec) DeepCopy() *OutputSpec {
	if in == nil {
		return nil
	}
	out := new(OutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDecision) DeepCopyInto(out *PolicyDecision) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(MatchedPolicyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDecision.
func (in *PolicyDecision) DeepCopy() *PolicyDecision {
	if in == nil {
		return nil
	}
	out := new(PolicyDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRef) DeepCopyInto(out *PolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRef.
func (in *PolicyRef) DeepCopy() *PolicyRef {
	if in == nil {
		return nil
	}
	out := new(PolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRules) DeepCopyInto(out *PolicyRules) {
	*out = *in
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedDomains != nil {
		in, out := &in.DeniedDomains, &out.DeniedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedCIDRs != nil {
		in, out := &in.DeniedCIDRs, &out.DeniedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedTools != nil {
		in, out := &in.DeniedTools, &out.DeniedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireHumanApproval != nil {
		in, out := &in.RequireHumanApproval, &out.RequireHumanApproval
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxNetworkRequests != nil {
		in, out := &in.MaxNetworkRequests, &out.MaxNetworkRequests
		*out = new(int32)
		**out = **in
	}
	if in.MaxToolCalls != nil {
		in, out := &in.MaxToolCalls, &out.MaxToolCalls
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRules.
func (in *PolicyRules) DeepCopy() *PolicyRules {
	if in == nil {
		return nil
	}
	out := new(PolicyRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyViolation) DeepCopyInto(out *PolicyViolation) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyViolation.
func (in *PolicyViolation) DeepCopy() *PolicyViolation {
	if in == nil {
		return nil
	}
	out := new(PolicyViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptConfigMapRef) DeepCopyInto(out *PromptConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptConfigMapRef.
func (in *PromptConfigMapRef) DeepCopy() *PromptConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(PromptConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfile) DeepCopyInto(out *RuntimeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfile.
func (in *RuntimeProfile) DeepCopy() *RuntimeProfile {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileContainerSpec) DeepCopyInto(out *RuntimeProfileContainerSpec) {
	*out = *in
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnlyRootFilesystem != nil {
		in, out := &in.ReadOnlyRootFilesystem, &out.ReadOnlyRootFilesystem
		*out = new(bool)
		**out = **in
	}
	if in.AllowPrivilegeEscalation != nil {
		in, out := &in.AllowPrivilegeEscalation, &out.AllowPrivilegeEscalation
		*out = new(bool)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(v1.Capabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileContainerSpec.
func (in *RuntimeProfileContainerSpec) DeepCopy() *RuntimeProfileContainerSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileList) DeepCopyInto(out *RuntimeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileList.
func (in *RuntimeProfileList) DeepCopy() *RuntimeProfileList {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfilePodSpec) DeepCopyInto(out *RuntimeProfilePodSpec) {
	*out = *in
	if in.SeccompProfile != nil {
		in, out := &in.SeccompProfile, &out.SeccompProfile
		*out = new(v1.SeccompProfile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfilePodSpec.
func (in *RuntimeProfilePodSpec) DeepCopy() *RuntimeProfilePodSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfilePodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileRef) DeepCopyInto(out *RuntimeProfileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileRef.
func (in *RuntimeProfileRef) DeepCopy() *RuntimeProfileRef {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileSidecar) DeepCopyInto(out *RuntimeProfileSidecar) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileSidecar.
func (in *RuntimeProfileSidecar) DeepCopy() *RuntimeProfileSidecar {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileSpec) DeepCopyInto(out *RuntimeProfileSpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(RuntimeProfileContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(RuntimeProfilePodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]RuntimeProfileSidecar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileSpec.
func (in *RuntimeProfileSpec) DeepCopy() *RuntimeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProfileStatus) DeepCopyInto(out *RuntimeProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProfileStatus.
func (in *RuntimeProfileStatus) DeepCopy() *RuntimeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSpec.
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionResult) DeepCopyInto(out *SessionResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionResult.
func (in *SessionResult) DeepCopy() *SessionResult {
	if in == nil {
		return nil
	}
	out := new(SessionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionTaskSpec) DeepCopyInto(out *SessionTaskSpec) {
	*out = *in
	if in.PromptConfigMapRef != nil {
		in, out := &in.PromptConfigMapRef, &out.PromptConfigMapRef
		*out = new(PromptConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionTaskSpec.
func (in *SessionTaskSpec) DeepCopy() *SessionTaskSpec {
	if in == nil {
		return nil
	}
	out := new(SessionTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionUsage) DeepCopyInto(out *SessionUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionUsage.
func (in *SessionUsage) DeepCopy() *SessionUsage {
	if in == nil {
		return nil
	}
	out := new(SessionUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPolicy) DeepCopyInto(out *ToolPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPolicy.
func (in *ToolPolicy) DeepCopy() *ToolPolicy {
	if in == nil {
		return nil
	}
	out := new(ToolPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPolicyList) DeepCopyInto(out *ToolPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToolPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPolicyList.
func (in *ToolPolicyList) DeepCopy() *ToolPolicyList {
	if in == nil {
		return nil
	}
	out := new(ToolPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPolicySpec) DeepCopyInto(out *ToolPolicySpec) {
	*out = *in
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedTools != nil {
		in, out := &in.DeniedTools, &out.DeniedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxToolCalls != nil {
		in, out := &in.MaxToolCalls, &out.MaxToolCalls
		*out = new(int32)
		**out = **in
	}
	if in.MaxCallsPerMinute != nil {
		in, out := &in.MaxCallsPerMinute, &out.MaxCallsPerMinute
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPolicySpec.
func (in *ToolPolicySpec) DeepCopy() *ToolPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ToolPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPolicyStatus) DeepCopyInto(out *ToolPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPolicyStatus.
func (in *ToolPolicyStatus) DeepCopy() *ToolPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ToolPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
